### ISSUE TITLE
Raw files 

### ISSUE THREAD

**Issue by JakobTopholt** [HTHNLNDN/flanposter#1]
As aFlan Crew member I would like if the raw files (such as adobe Illustrator) were included as it would then be a lot easier for me to make slight edits to the awesome posters.

**Comment by HTHNLNDN** [comment]
Jeg kan godt smide dig de rå, problemet er bare at det hele er lavet i en
gimp fil for at preserve patterns 🤣

**Comment by HTHNLNDN** [comment]
Raw ligger i samme mappe med extension .xcf @JakobTopholt
